services:
  savings-app:
    image: savings-system
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - postgres
    environment:
      - POSTGRES_URI=postgresql://postgres:1234@postgres:5432/kopkad_db
      - SECRET_KEY=top_secret_key
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRES_IN=15
      - SMTP_SERVER=smtp.example.com
      - SMTP_PORT=587
      - SMTP_USERNAME=user@example.com
      - SMTP_PASSWORD=password
      - BASE_DIR=/app
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=savings_db