# Optional Docker Compose for Redis (for development/local testing)
# Usage: docker-compose -f docker-compose.redis.yml up -d

version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: kopkad-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis-data:
    driver: local
